INSERT INTO [USER]
    (name, email)
VALUES
    ("Trudey Longmead","tlongmead0@epa.gov"),
    ("Gene Cordelle","gcordelle1@fastcompany.com"),
    ("Brandie Stutely","bstutely2@forbes.com"),
    ("Loise Haxbie","lhaxbie3@hao123.com"),
    ("Arie Dohmer","adohmer4@gravatar.com"),
    ("Kermy Kraft","kkraft5@smugmug.com"),
    ("Bartel Raggles","braggles6@japanpost.jp"),
    ("Syd Heintsch","sheintsch7@360.cn"),
    ("Auberon Bavin","abavin8@blogger.com"),
    ("Sidonia Skegg","sskegg9@buzzfeed.com"),
    ("Laura Whellams","lwhellamsa@deliciousdays.com"),
    ("Alfonso Gatherer","agathererb@gmpg.org"),
    ("Shanda Carratt","scarrattc@privacy.gov.au"),
    ("Andrey Medgwick","amedgwickd@homestead.com"),
    ("Linnea Klimas","lklimase@craigslist.org"),
    ("Forest Lawland","flawlandf@storify.com"),
    ("Gates Farndell","gfarndellg@xing.com"),
    ("Tricia Nevison","tnevisonh@toplist.cz"),
    ("Roseanne Ashelford","rashelfordi@jiathis.com"),
    ("Gale Tabary","gtabaryj@ow.ly"),
    ("Kellyann Lowthian","klowthiank@homestead.com"),
    ("Renell Spedroni","rspedronil@ihg.com"),
    ("Egor Pepys","epepysm@abc.net.au"),
    ("Griffin Hallgarth","ghallgarthn@uol.com.br"),
    ("Beret Aldwich","baldwicho@blinklist.com"),
    ("Demetrius Dovydenas","ddovydenasp@oaic.gov.au"),
    ("Trstram Piwall","tpiwallq@tiny.cc"),
    ("Isahella Vasishchev","ivasishchevr@ovh.net"),
    ("Reina Fleisch","rfleischs@yahoo.co.jp"),
    ("Ira Firebrace","ifirebracet@alexa.com"),
    ("Kayla Sanham","ksanhamu@fema.gov"),
    ("Christen Spellissy","cspellissyv@de.vu"),
    ("Shirley Petyankin","spetyankinw@redcross.org"),
    ("Brigida Ivshin","bivshinx@paginegialle.it"),
    ("Dagmar Gayton","dgaytony@imageshack.us"),
    ("Genovera Walesa","gwalesaz@vkontakte.ru"),
    ("Yovonnda Clemanceau","yclemanceau10@themeforest.net"),
    ("Bertine Francescuccio","bfrancescuccio11@hatena.ne.jp"),
    ("Cletus Butterfill","cbutterfill12@w3.org");
	
INSERT INTO SELLER
    (email,bio,photo)
VALUES
    ("tlongmead0@epa.gov","Etiam vel augue. Vestibulum rutrum rutrum neque.","http://dummyimage.com/363x314.jpg/ff4444/ffffff"),
    ("gcordelle1@fastcompany.com","In est risus, auctor sed, tristique in, tempus sit amet, sem.","http://dummyimage.com/297x486.jpg/cc0000/ffffff"),
    ("bstutely2@forbes.com","Fusce consequat. Nulla nisl.","http://dummyimage.com/349x445.jpg/5fa2dd/ffffff"),
    ("lhaxbie3@hao123.com","Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.","http://dummyimage.com/461x302.jpg/ff4444/ffffff"),
    ("adohmer4@gravatar.com","Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.","http://dummyimage.com/260x486.jpg/5fa2dd/ffffff"),
    ("kkraft5@smugmug.com","Nulla ut erat id mauris vulputate elementum. Nullam varius.","http://dummyimage.com/340x266.jpg/cc0000/ffffff"),
    ("braggles6@japanpost.jp","Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.","http://dummyimage.com/317x483.jpg/dddddd/000000"),
    ("sheintsch7@360.cn","Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.","http://dummyimage.com/486x252.jpg/dddddd/000000"),
    ("abavin8@blogger.com","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.","http://dummyimage.com/280x489.jpg/ff4444/ffffff"),
    ("sskegg9@buzzfeed.com","Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.","http://dummyimage.com/457x282.jpg/cc0000/ffffff"),
    ("lwhellamsa@deliciousdays.com","Aliquam non mauris.","http://dummyimage.com/469x284.jpg/dddddd/000000"),
    ("agathererb@gmpg.org","Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.","http://dummyimage.com/277x366.jpg/ff4444/ffffff"),
    ("scarrattc@privacy.gov.au","In hac habitasse platea dictumst.","http://dummyimage.com/463x441.jpg/5fa2dd/ffffff"),
    ("amedgwickd@homestead.com","Nulla tellus. In sagittis dui vel nisl. Duis ac nibh.","http://dummyimage.com/410x372.jpg/5fa2dd/ffffff"),
    ("lklimase@craigslist.org","Nulla tellus. In sagittis dui vel nisl.","http://dummyimage.com/389x361.jpg/ff4444/ffffff"),
    ("flawlandf@storify.com","Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.","http://dummyimage.com/467x320.jpg/cc0000/ffffff"),
    ("gfarndellg@xing.com","Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","http://dummyimage.com/377x281.jpg/dddddd/000000"),
    ("tnevisonh@toplist.cz","Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.","http://dummyimage.com/322x500.jpg/5fa2dd/ffffff"),
    ("rashelfordi@jiathis.com","Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.","http://dummyimage.com/329x348.jpg/5fa2dd/ffffff"),
    ("gtabaryj@ow.ly","Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.","http://dummyimage.com/283x259.jpg/dddddd/000000"),
    ("klowthiank@homestead.com","Suspendisse potenti. In eleifend quam a odio.","http://dummyimage.com/451x264.jpg/cc0000/ffffff"),
    ("rspedronil@ihg.com","Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.","http://dummyimage.com/318x480.jpg/5fa2dd/ffffff"),
    ("epepysm@abc.net.au","Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.","http://dummyimage.com/297x426.jpg/ff4444/ffffff"),
    ("ghallgarthn@uol.com.br","In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.","http://dummyimage.com/444x391.jpg/ff4444/ffffff"),
    ("baldwicho@blinklist.com","Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","http://dummyimage.com/427x300.jpg/5fa2dd/ffffff"),
    ("ddovydenasp@oaic.gov.au","Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.","http://dummyimage.com/307x444.jpg/cc0000/ffffff"),
    ("tpiwallq@tiny.cc","Quisque porta volutpat erat.","http://dummyimage.com/299x352.jpg/ff4444/ffffff"),
    ("ivasishchevr@ovh.net","Curabitur gravida nisi at nibh.","http://dummyimage.com/406x348.jpg/dddddd/000000"),
    ("rfleischs@yahoo.co.jp","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.","http://dummyimage.com/297x269.jpg/cc0000/ffffff"),
    ("ifirebracet@alexa.com","Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.","http://dummyimage.com/305x467.jpg/dddddd/000000"),
    ("ksanhamu@fema.gov","Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.","http://dummyimage.com/340x342.jpg/ff4444/ffffff"),
    ("cspellissyv@de.vu","Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.","http://dummyimage.com/263x373.jpg/5fa2dd/ffffff"),
    ("spetyankinw@redcross.org","Integer ac leo. Pellentesque ultrices mattis odio.","http://dummyimage.com/369x484.jpg/cc0000/ffffff"),
    ("bivshinx@paginegialle.it","Phasellus sit amet erat. Nulla tempus.","http://dummyimage.com/424x257.jpg/cc0000/ffffff"),
    ("dgaytony@imageshack.us","Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.","http://dummyimage.com/465x284.jpg/cc0000/ffffff"),
    ("gwalesaz@vkontakte.ru","Etiam justo. Etiam pretium iaculis justo.","http://dummyimage.com/476x434.jpg/ff4444/ffffff"),
    ("yclemanceau10@themeforest.net","Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.","http://dummyimage.com/257x359.jpg/5fa2dd/ffffff"),
    ("bfrancescuccio11@hatena.ne.jp","Suspendisse potenti. Cras in purus eu magna vulputate luctus.","http://dummyimage.com/456x314.jpg/5fa2dd/ffffff"),
    ("cbutterfill12@w3.org","Cras in purus eu magna vulputate luctus.","http://dummyimage.com/463x264.jpg/5fa2dd/ffffff");

INSERT INTO STORE
    (seller_email,name,banner,description)
VALUES
    ("tlongmead0@epa.gov","Goyette Group","http://dummyimage.com/941x483.jpg/ff4444/ffffff","Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst."),
    ("gcordelle1@fastcompany.com","Vandervort, Beier and Mraz","http://dummyimage.com/919x405.jpg/ff4444/ffffff","Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis."),
    ("bstutely2@forbes.com","Bogisich and Sons","http://dummyimage.com/1067x318.jpg/ff4444/ffffff","Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."),
    ("lhaxbie3@hao123.com","Keebler-Schultz","http://dummyimage.com/1091x321.jpg/cc0000/ffffff","Aenean lectus. Pellentesque eget nunc."),
    ("adohmer4@gravatar.com","Pfeffer-Kris","http://dummyimage.com/1080x466.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("kkraft5@smugmug.com","Breitenberg-VonRueden","http://dummyimage.com/856x439.jpg/ff4444/ffffff","Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat."),
    ("braggles6@japanpost.jp","Ortiz-Parisian","http://dummyimage.com/966x394.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("sheintsch7@360.cn","Wehner, Schulist and Morissette","http://dummyimage.com/994x303.jpg/dddddd/000000","Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum."),
    ("abavin8@blogger.com","Sipes-Waelchi","http://dummyimage.com/804x391.jpg/dddddd/000000","Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat."),
    ("sskegg9@buzzfeed.com","Ryan LLC","http://dummyimage.com/873x252.jpg/dddddd/000000","###############################################################################################################################################################################################################################################################"),
    ("lwhellamsa@deliciousdays.com","Jakubowski, Veum and Welch","http://dummyimage.com/855x451.jpg/cc0000/ffffff","Donec posuere metus vitae ipsum."),
    ("agathererb@gmpg.org","Hirthe-Simonis","http://dummyimage.com/1114x275.jpg/dddddd/000000","Vivamus in felis eu sapien cursus vestibulum. Proin eu mi."),
    ("scarrattc@privacy.gov.au","Sipes-Wilderman","http://dummyimage.com/813x370.jpg/cc0000/ffffff","In hac habitasse platea dictumst."),
    ("amedgwickd@homestead.com","Leuschke-Weissnat","http://dummyimage.com/1192x362.jpg/5fa2dd/ffffff","Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus."),
    ("lklimase@craigslist.org","Gleichner-Koelpin","http://dummyimage.com/1087x475.jpg/cc0000/ffffff","Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est."),
    ("flawlandf@storify.com","Nicolas, Gleichner and Wiegand","http://dummyimage.com/1090x324.jpg/5fa2dd/ffffff","Nunc rhoncus dui vel sem."),
    ("gfarndellg@xing.com","Ferry, Gerhold and Thiel","http://dummyimage.com/961x250.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("tnevisonh@toplist.cz","O'Conner-Stark","http://dummyimage.com/1044x473.jpg/cc0000/ffffff","Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo."),
    ("rashelfordi@jiathis.com","Fisher, Marquardt and Kulas","http://dummyimage.com/1135x290.jpg/dddddd/000000","###############################################################################################################################################################################################################################################################"),
    ("gtabaryj@ow.ly","Krajcik Inc","http://dummyimage.com/835x452.jpg/5fa2dd/ffffff","Phasellus sit amet erat."),
    ("klowthiank@homestead.com","Kohler-Lehner","http://dummyimage.com/1082x377.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("rspedronil@ihg.com","Leuschke-Hermann","http://dummyimage.com/1194x362.jpg/dddddd/000000","###############################################################################################################################################################################################################################################################"),
    ("epepysm@abc.net.au","Littel Inc","http://dummyimage.com/820x389.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("ghallgarthn@uol.com.br","Abernathy-Carter","http://dummyimage.com/1025x435.jpg/ff4444/ffffff","Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus."),
    ("baldwicho@blinklist.com","Kulas, Simonis and Smitham","http://dummyimage.com/1015x379.jpg/dddddd/000000","Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo."),
    ("ddovydenasp@oaic.gov.au","Walter-O'Keefe","http://dummyimage.com/1172x253.jpg/dddddd/000000","In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy."),
    ("tpiwallq@tiny.cc","Beer Inc","http://dummyimage.com/1144x331.jpg/5fa2dd/ffffff","###############################################################################################################################################################################################################################################################"),
    ("ivasishchevr@ovh.net","Swaniawski and Sons","http://dummyimage.com/1078x442.jpg/5fa2dd/ffffff","Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim."),
    ("rfleischs@yahoo.co.jp","Dicki-Simonis","http://dummyimage.com/931x362.jpg/cc0000/ffffff","###############################################################################################################################################################################################################################################################"),
    ("ifirebracet@alexa.com","Quigley Group","http://dummyimage.com/882x384.jpg/ff4444/ffffff","Sed ante. Vivamus tortor."),
    ("ksanhamu@fema.gov","Murazik Group","http://dummyimage.com/823x430.jpg/ff4444/ffffff","###############################################################################################################################################################################################################################################################"),
    ("cspellissyv@de.vu","Russel, Schmeler and Thiel","http://dummyimage.com/1029x329.jpg/cc0000/ffffff","Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh."),
    ("spetyankinw@redcross.org","Senger and Sons","http://dummyimage.com/885x314.jpg/ff4444/ffffff","Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui."),
    ("bivshinx@paginegialle.it","Walter, Hilll and Murray","http://dummyimage.com/1155x346.jpg/ff4444/ffffff","Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo."),
    ("dgaytony@imageshack.us","Olson LLC","http://dummyimage.com/924x392.jpg/cc0000/ffffff","Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus."),
    ("gwalesaz@vkontakte.ru","Padberg and Sons","http://dummyimage.com/1114x499.jpg/5fa2dd/ffffff","Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."),
    ("yclemanceau10@themeforest.net","Hirthe and Sons","http://dummyimage.com/975x302.jpg/cc0000/ffffff","Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum."),
    ("bfrancescuccio11@hatena.ne.jp","Ledner Inc","http://dummyimage.com/1100x298.jpg/cc0000/ffffff","Nunc purus. Phasellus in felis."),
    ("cbutterfill12@w3.org","Mohr, Mann and Weissnat","http://dummyimage.com/1174x271.jpg/cc0000/ffffff","###############################################################################################################################################################################################################################################################");

